# Ollama API integration
# Handles LLM calls to local Llama 3 model
import logging 
import httpx
import os
from typing import Optional, List
from .logger import setup_logger

DEFAULT_LLM_MODEL = os.getenv("LLM_MODEL", "llama3.2:3b")  # Default to llama3.2 3B if not specified in .env
OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")

logger = setup_logger(__name__)

async def generate_response(query: str, context: str, conversation_history: Optional[List] = None) -> str:
    """     
    Generate a response from the LLM based on the query and retrieved context.
    
    Args:
        query (str): The user's query string.
        context (str): The relevant context retrieved from the knowledge base.
    
    Returns:
        str: The answer generated by the LLM.
        
    """
    history_text = ""
    if conversation_history:
        history_text = "\n\nPrevious conversation (for context):\n"
        for item in conversation_history:
            history_text += f"User: {item['query']}\n"
            history_text += f"Assistant: {item['answer']}\n\n"
        logger.info(f"Using {len(conversation_history)} previous interactions for context")
    else:
        logger.info("No conversation history provided")
    
    prompt = f"""You are an AI assistant with access to the user's personal Obsidian vault.

Context from their notes:
{context}
{history_text}
Current question: {query}

IMPORTANT: If this question refers to something from the previous conversation (like "it", "that", "tell me more"), use the conversation history above to understand what the user is referring to. Provide a helpful answer based on both the context and conversation history.

Answer:"""
    try:
        logger.info(f"Generating response with context length: {len(context)} characters")
        
        # Async HTTP call to Ollama API
        async with httpx.AsyncClient(timeout=60.0) as client:
            response = await client.post(
                f"{OLLAMA_HOST}/api/chat",
                json={
                    "model": DEFAULT_LLM_MODEL,
                    "messages": [
                        {"role": "system", "content": "You are a helpful assistant that provides answers based on the user's personal notes."},
                        {"role": "user", "content": prompt}
                    ],
                    "stream": False,
                    "options": {
                        "temperature": 0.2,
                        "num_predict": 500
                    }
                }
            )
            response.raise_for_status()
            data = response.json()
            return data['message']['content']
            
    except httpx.HTTPError as e:
        logger.error(f"HTTP error generating response: {e}")
        return "I'm sorry, I couldn't connect to the LLM service."
    except Exception as e:
        logger.error(f"Error generating response: {e}")
        return "I'm sorry, I couldn't generate a response at this time."


async def check_ollama_health() -> bool:
    """Check if the Ollama LLM service is reachable and operational"""
    try:
        # Async health check using httpx
        async with httpx.AsyncClient(timeout=5.0) as client:
            response = await client.get(f"{OLLAMA_HOST}/api/tags")
            response.raise_for_status()
            models = response.json().get('models', [])
            
            # Check if our model is available
            model_names = [model['name'] for model in models]
            if DEFAULT_LLM_MODEL not in model_names:
                logger.warning(f"Specified LLM model '{DEFAULT_LLM_MODEL}' not found in Ollama. Available models: {model_names}")
                return False
                
            logger.info("Ollama health check successful")
            return True
            
    except httpx.HTTPError as e:
        logger.error(f"Ollama health check failed (HTTP): {e}")
        return False
    except Exception as e:
        logger.error(f"Ollama health check failed: {e}")
        return False
