# Ollama API integration
# Handles LLM calls to local Llama 3 model
import logging 
import ollama
import os 
from .logger import setup_logger

DEFAULT_LLM_MODEL = os.getenv("LLM_MODEL", "llama3.2:3B")  # Default to llama3.2 3B if not specified in .env

logger = setup_logger(__name__)

def generate_response(query: str, context: str) -> str:
    """
    Generate a response from the LLM based on the query and retrieved context.
    
    Args:
        query (str): The user's query string.
        context (str): The relevant context retrieved from the knowledge base.
    
    Returns:
        str: The answer generated by the LLM.
    """
    prompt = f"""You are an AI assistant with access to the user's personal Obsidian vault.

        Context from their notes:
        {context}

        Question: {query}

        Provide a helpful answer based on the context above. If the context doesn't contain relevant information, say so clearly.

        Answer:"""
    try:
        logger.info(f"Generating response with context length: {len(context)} characters")
        response = ollama.chat(
            model = DEFAULT_LLM_MODEL,
            messages = [
                {"role": "system", "content": "You are a helpful assistant that provides answers based on the user's personal notes."},
                {"role": "user", "content": prompt}
            ],
            temperature = 0.2,  # Lower temperature for more focused responses
            num_predict = 500  # Limit response length to prevent excessively long answers
        )
        return response['message']['content']
    except Exception as e:
        logger.error(f"Error generating response: {e}")
        return "I'm sorry, I couldn't generate a response at this time."


def check_ollama_health() -> bool:
    """Check if the Ollama LLM service is reachable and operational"""
    try:
        # attempt to get a response from the LLM to confirm it's working
        models_list = ollama.list()
        if DEFAULT_LLM_MODEL not in [model['name'] for model in models_list]:
            logger.warning(f"Specified LLM model '{DEFAULT_LLM_MODEL}' not found in Ollama. Available models: {[model['name'] for model in models_list]}")
            return False
        logger.info("Ollama health check successful")
        return True
    except Exception as e:
        logger.error(f"Ollama health check failed: {e}")
        return False
