# Shared Pydantic models for API requests and responses.
# Keeps data structures consistent between the brain server and edge client.
from pydantic import BaseModel, Field
from typing import List, Optional


# --- Request models ---

class IngestRequest(BaseModel):
    """Request body for POST /ingest."""
    file_path: str = Field(..., description="Path to the file to ingest")
    metadata: Optional[dict] = Field(None, description="Optional metadata for the file")


class QueryRequest(BaseModel):
    """Request body for POST /query."""
    query: str = Field(..., description="The query string to search against the knowledge base")
    top_k: int = Field(5, description="Number of top results to return from similarity search")
    filter_metadata: Optional[dict] = Field(None, description="Optional metadata filters for similarity search")
    conversation_history: Optional[List[dict]] = Field(None, description="Optional conversation history for context-aware responses")


class DeleteDocumentRequest(BaseModel):
    """Request body for DELETE /documents."""
    file_path: str = Field(..., description="Path of the document whose chunks should be removed")


# --- Response models ---

class IngestResponse(BaseModel):
    """Response body for POST /ingest."""
    success: bool = Field(..., description="Whether the ingestion succeeded")
    message: Optional[str] = Field(None, description="Additional information about the result")
    file_path: str = Field(..., description="The file path that was ingested")
    chunks_added: int = Field(..., description="Number of chunks added to the knowledge base")
    document_id: Optional[str] = Field(None, description="Unique ID assigned to the ingested document")


class SourceDocument(BaseModel):
    """A source document referenced in a query answer."""
    document_id: str = Field(..., description="Unique ID of the source document")
    content_snippet: str = Field(..., description="Snippet of content relevant to the query")
    metadata: Optional[dict] = Field(None, description="Metadata associated with the source document")
    similarity_score: float = Field(..., description="Similarity score used for ranking relevance")


class QueryResponse(BaseModel):
    """Response body for POST /query."""
    query: str = Field(..., description="The original query string")
    answer: str = Field(..., description="Answer generated by the LLM from the retrieved context")
    sources: List[SourceDocument] = Field(..., description="Source documents that informed the answer")
    processing_time: float = Field(..., description="Time taken to process the query, in seconds")


class DocumentInfo(BaseModel):
    """Summary of a single indexed document."""
    file_path: str = Field(..., description="Path of the source file")
    file_name: str = Field(..., description="Base name of the source file")
    chunk_count: int = Field(..., description="Number of chunks stored for this document")


class DocumentListResponse(BaseModel):
    """Response body for GET /documents."""
    documents: List[DocumentInfo] = Field(..., description="Indexed documents")
    total: int = Field(..., description="Total number of indexed documents")


class DeleteDocumentResponse(BaseModel):
    """Response body for DELETE /documents."""
    success: bool = Field(..., description="Whether the deletion succeeded")
    file_path: str = Field(..., description="Path of the document that was targeted")
    chunks_deleted: int = Field(..., description="Number of chunks removed")
    message: Optional[str] = Field(None, description="Additional information about the result")


class StatsResponse(BaseModel):
    """Response body for GET /stats."""
    collection_name: str = Field(..., description="Name of the ChromaDB collection")
    total_chunks: int = Field(..., description="Total number of chunks in the collection")
    total_documents: int = Field(..., description="Number of distinct source documents")


class HealthCheckResponse(BaseModel):
    """Response body for GET /health."""
    status: str = Field(..., description="Overall server status: 'healthy' or 'degraded'")
    start_time: str = Field(..., description="Timestamp when the server was started")
    uptime: float = Field(..., description="Server uptime in seconds")
    ollama_status: bool = Field(..., description="Whether the Ollama LLM service is reachable")
    chroma_connected: bool = Field(..., description="Whether the ChromaDB instance is reachable")
