# Shared Pydantic models for API requests/responses
# Ensures consistent data structures between Brain and Edge
from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional



######################## Reuqest models ########################
class IngestRequest(BaseModel):
    """ Request model for /ingest endpoint """ 
    file_path: str = Field(..., description="Path to the file to ingest")
    metadata: Optional[dict] = Field(None, description="Optional metadata for the file")

class QueryRequest(BaseModel):
    """ Request model for /query endpoint """ 
    query: str = Field(..., description="The query string to search against the knowledge base")
    top_k: int = Field(5, description="Number of top results to return from similarity search")
    filter_metadata: Optional[dict] = Field(None, description="Optional metadata filters for similarity search")
    conversation_history: Optional[List[dict]] = Field(None, description="Optional conversation history for context-aware responses")

########################## Response models ########################
class IngestResponse(BaseModel):
    """ Response model for /ingest endpoint """ 
    success: bool = Field(..., description="Indicates if the ingestion was successful")
    message: Optional[str] = Field(None, description="Additional information about the ingestion result")
    file_path: str = Field(..., description="The file path that was ingested")
    chunks_added: int = Field(..., description="Number of chunks added to the knowledge base")
    document_id: str = Field(..., description="Unique ID assigned to the ingested document")





class SourceDocument(BaseModel):
    """ Model for source documents included in the QueryResponse """
    document_id: str = Field(..., description="Unique ID of the source document in the knowledge base")
    content_snippet: str = Field(..., description="A snippet of the content from the source document that was relevant to the query")
    metadata: Optional[dict] = Field(None, description="Optional metadata associated with the source document")
    similarity_score: float = Field(..., description="Similarity score between the source document and the query, used for ranking relevance")

# Response data model for /query endpoint
class QueryResponse(BaseModel):
    """ Response model for / query endpoint """
    # echo back the original query for reference
    query: str = Field(..., description="The original query string")
    answer: str = Field(..., description="The answer generated by the LLM based on the query and retrieved context")
    sources: List[SourceDocument] = Field(..., description="List of source documents retrieved from the knowledge base that informed the answer")  
    processing_time: float = Field(..., description="Time taken to process the query and generate the response in seconds")


class HealthCheckResponse(BaseModel):
    """ Response model for health check endpoint """
    status: str = Field(..., description="Health status of the Brain Server, e.g., 'ok' or 'error'")
    start_time: str = Field(..., description="Timestamp when the Brain Server was started")
    uptime: float = Field(..., description="Uptime of the Brain Server in seconds")
    ollama_status: bool = Field(..., description="Indicates if the Ollama LLM service is reachable and operational")
    chroma_connected: bool = Field(..., description="Indicates if the Brain Server is successfully connected to the ChromaDB instance")




